//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DataExpressWeb.WebServiceReport {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GenerarReporteSoap", Namespace="http://tempuri.org/")]
    public partial class GenerarReporte : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GeneraReporteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GenerarReporte() {
            this.Url = global::DataExpressWeb.Properties.Settings.Default.DataExpressWeb_WebServiceReport_GenerarReporte;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GeneraReporteCompletedEventHandler GeneraReporteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GeneraReporte", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GeneraReporte(string sucursal, string dir, string fecha, string fechanom, string tipreporte, string where, string ptoemi, int Id, string auxRuta, string usuario, string rfcrec) {
            this.Invoke("GeneraReporte", new object[] {
                        sucursal,
                        dir,
                        fecha,
                        fechanom,
                        tipreporte,
                        where,
                        ptoemi,
                        Id,
                        auxRuta,
                        usuario,
                        rfcrec});
        }
        
        /// <remarks/>
        public void GeneraReporteAsync(string sucursal, string dir, string fecha, string fechanom, string tipreporte, string where, string ptoemi, int Id, string auxRuta, string usuario, string rfcrec) {
            this.GeneraReporteAsync(sucursal, dir, fecha, fechanom, tipreporte, where, ptoemi, Id, auxRuta, usuario, rfcrec, null);
        }
        
        /// <remarks/>
        public void GeneraReporteAsync(string sucursal, string dir, string fecha, string fechanom, string tipreporte, string where, string ptoemi, int Id, string auxRuta, string usuario, string rfcrec, object userState) {
            if ((this.GeneraReporteOperationCompleted == null)) {
                this.GeneraReporteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneraReporteOperationCompleted);
            }
            this.InvokeAsync("GeneraReporte", new object[] {
                        sucursal,
                        dir,
                        fecha,
                        fechanom,
                        tipreporte,
                        where,
                        ptoemi,
                        Id,
                        auxRuta,
                        usuario,
                        rfcrec}, this.GeneraReporteOperationCompleted, userState);
        }
        
        private void OnGeneraReporteOperationCompleted(object arg) {
            if ((this.GeneraReporteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneraReporteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GeneraReporteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591